import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import ProfilePic from '../../public/images/profile/sebb.png'
import AnimatedText from '@/components/AnimatedText'


export default function Home() {
  return (
    <>
      <Head>
        <title>Sebby Apudo creative developer portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <Image src={ProfilePic} alt="Sebby Apudo" className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left'/>
              <p>
                I am freelance creative developer, 3D Animator and graphics designer.
                My goal is to combine creative thinking and design with an analytical approach to solve problems at the intersection of business and technology. 
                Feel free to drop me a line,
                Cheers : )            
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
